# Register Field Types

# FieldType: Integer
# Documentation: https://github.com/admin-interface/admin-interface/wiki/Integer-FieldType
Integer: "[module] @admin-interface/addons/dist/FieldType/Integer/Integer.js"

# FieldType: String
# Documentation: https://github.com/admin-interface/admin-interface/wiki/String-FieldType
String: "[module] @admin-interface/addons/dist/FieldType/String/String.js"

# FieldType: Reference
# Documentation: https://github.com/admin-interface/admin-interface/wiki/Reference-FieldType
Reference: "[module] @admin-interface/addons/dist/FieldType/Reference/Reference.js"

# FieldType: Date
# Documentation: https://github.com/admin-interface/admin-interface/wiki/Date-FieldType
Date: "[module] @admin-interface/addons/dist/FieldType/Date/Date.js"

# FieldType: Select
# Documentation: https://github.com/admin-interface/admin-interface/wiki/Select-FieldType
Select: "[module] @admin-interface/addons/dist/FieldType/Select/Select.js"

# FieldType: Textarea
# Documentation: https://github.com/admin-interface/admin-interface/wiki/Textarea-FieldType
Textarea: "[module] @admin-interface/addons/dist/FieldType/Textarea/Textarea.js"

# FieldType: Tinymce
# Documentation: https://github.com/admin-interface/admin-interface/wiki/Tinymce-FieldType
Tinymce: "[module] @admin-interface/addons/dist/FieldType/Tinymce/Tinymce.js"