# Folders have Jade views
views: []

# Default context
locals:
    # Base jade dir
    basedir: ./../views

    # Branding
    branding:
        # Site title
        siteName: Admin Interface
    blocks: {}

# Static url path
staticPath: /static

# Models url path
modelPath: /model

# FieldTypes url path
fieldPath: /field_type

# API url path
apiPath: /api

# Widgets url path
widgetPath: /widget
